Mod 2 d 3 d mappers
pyfsi/coconut pull request #118
Opened 2021-05-21 14:03 UTC by mvervaec

-Description:
The axisymmetric mappers 'axisymmetric_2d_to_3d' and 'axisymmetric_3d_to_2d' are adapted, so the user can select wither the case has to be mapped with 'wedge axisymmetric' (e.g. OpenFOAM axisymmetric) or a full 3D case (e.g. tube OpenFOAM3d-Abaqus2d). The name of the mappers in this branch to review are: 'axisymmetric_2d_to_3d_mod' and 'axisymmetric_3d_to_2d_mod'.  The flag installed to switch from 3d to wedge and vice versa is called: 'wedge'

-Tests:
 Unit tests are executed. To swap from 3d to wedge and vice versa has been tested and checked with the gui. The name of the unit tests are: 'test_axisymmetric_2d_to_3d_mod' and 'test_axisymmetric_3d_to_2d_mod' 

-Checklist:
Check if the mappers work with flag 'wedge'

2021-05-25 06:53 UTC, joris13 requested changes
- The idea is not to make a ...Mod version. The code has to be integrated in the axisymmetric_3d_to_2d class, without changing the filename, such that there is only 1 file and not a "normal version" and a "mod version"
- Do not use a bool "wedge" as parameter and then if (wedge) ... else ... in the code, but really make it one code with an angle as parameter (default 2pi) and then using -angle/2 to +angle/2 for all the code.

2021-06-04 11:58 UTC, nicolasdlss reviewed
- _`examples/post_processing/animate_example.py`_ should not be changed
- _`examples/tube_fluent3d_abaqus2d/parameters.json`_ should not be changed (360 is default)
- The formatting in the files is a lot better, but there are still improvements possible. Using the `CTRL` + `ALT` + `L` automatically correctly formats your file.
- Don't forget to modify the documentation accordingly
- In fact these are not very good tests, because they use the same code as the code they test... But I understand it's hard to make good tests for this. This is also the way Toon did it. One option would be to check the number of points for each axial coordinate an see if they are equal to `n_tangential`, check that they are on a circle with the correct radius, check that the angle between them is correct and check that the angle between the furthest and the largest is correct.
- In order to also test the full circle, I would add 
```
    def test_initialize_360(self):
        self.parameters['settings'].pop('angle')
        self.test_initialize()
```
After the initialize test.

2021-06-04 11:58 UTC, nicolasdlss commented on tests/mappers/test_axisymmetric_2d_to_3d.py
> +            print( key + ' is set on ' + str(self.angle) + ' degrees')
Modify this to  `angle = self.parameters['settings'].get('angle', 360)` (I would not make angle a class variable, as you only use it locally)

2021-06-04 11:58 UTC, nicolasdlss commented on coupling_components/mappers/axisymmetric_2d_to_3d.py
> +        self.angle  = self.settings.get('angle',360) #angle is set in degrees
- The formatting in the files is a lot better, but there are still improvements possible. Using the `CTRL` + `ALT` + `L` automatically correctly formats your file. (applies to all files)

2021-06-04 11:58 UTC, nicolasdlss commented on examples/post_processing/animate_example.py
> +case_paths = ['tube_fluent3d_abaqus2d/case_results.pickle']
- _`examples/post_processing/animate_example.py`_ should not be changed

2021-06-04 11:58 UTC, nicolasdlss commented on examples/tube_fluent3d_abaqus2d/parameters.json
> +                      "n_tangential": 10
- _`examples/tube_fluent3d_abaqus2d/parameters.json`_ should not be changed (360 is default)

2021-06-04 11:58 UTC, nicolasdlss commented on tests/mappers/test_axisymmetric_3d_to_2d.py
> +            print(key + ' is set on ' + str(self.angle) + ' degrees')
Modify this to angle = self.parameters['settings'].get('angle', 360) (I would not make angle a class variable, as you only use it locally)

2021-07-01 09:17 UTC, nicolasdlss commented
The relevant files from this pull request have been copied to a new pull request update mappers and test #131.

2021-07-01 09:17 UTC, closed without merging